name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run herokuish buidpack test
      run: |
        /bin/herokuish buildpack test
    container:
      image: gliderlabs/herokuish
