name: Ruby
on: [push]
jobs:
  test:
    name: App Tests
    runs-on: ubuntu-latest
    container: circleci/ruby:2.6.5-node-browsers
    
    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      
    steps:
    - uses: actions/checkout@v1

    - name: Install Fonts
      run: |
        sudo apt-get update && sudo apt-get -y install gsfonts

    - name: Build App
      env:
        PGHOST: postgres
        PGUSER: postgres
        RAILS_ENV: test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        yarn install
        bin/rails db:setup

    - name: Run App Tests
      env:
        PGHOST: postgres
        PGUSER: postgres
        RAILS_ENV: test
      run: bundle exec rails test

    - name: Run System Tests
      env:
        PGHOST: postgres
        PGUSER: postgres
        RAILS_ENV: test
        HEADLESS: true
      run: bundle exec rails test:system
