name: Ruby

on: [push]

jobs:
  build:
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - name: Build app using buildpack
      run: |
        docker run -it -v --cidfile /tmp/built.cid $GITHUB_WORKSPACE:/tmp/app gliderlabs/herokuish:latest /build
        docker run -it -v $(</tmp/built.cid) /exec bundle exec rails test
