name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run rails test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rails test
    container:
      image: ruby:2.6.5
