name: Ruby

on: [push]

jobs:
  build:
    runs-on: [ubuntu-18.04]
    services:
      postgres:
        image: postgres:11.5
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        
    steps:
    - uses: actions/checkout@v2
    - name: Build app using herokuish
      run: docker run --cidfile /tmp/built.cid -i -v $GITHUB_WORKSPACE:/tmp/app gliderlabs/herokuish:latest /build 
    - name: Commit image
      run: docker commit $(</tmp/built.cid) app:latest
    - name: Run tests
      run: docker run -i -p ${{ job.services.postgres.ports[5432] }}:5432 -e PGHOST=localhost -e PGUSER=postgres app:latest /exec bundle exec rails test
