name: Ruby

on: [push]

jobs:
  build:
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - name: Build app using buildpack
      run: |
        docker run --cidfile /tmp/built.cid -i -v $GITHUB_WORKSPACE:/tmp/app gliderlabs/herokuish:latest /build 
        docker commit $(</tmp/built.cid) app:latest
        docker run -i -v app:latest /exec bundle exec rails test
